name: CI

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-riscv:
    name: Check RISC-V
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]
        printer: ["rtt", "uart"]
        include:
          - chip: esp32c3
            printer: "jtag_serial"
          - chip: esp32c6
            printer: "jtag_serial"
          - chip: esp32h2
            printer: "jtag_serial"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src
          default: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: -Zbuild-std=core --no-default-features --target=riscv32imc-unknown-none-elf --features=${{ matrix.chip }},${{ matrix.printer }}

  check-xtensa:
    name: Check Xtensa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [esp32, esp32s2, esp32s3]
        printer: ["rtt", "uart"]
        include:
          - chip: esp32s3
            printer: "jtag_serial"
    steps:
      - uses: actions/checkout@v2
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: false
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: -Zbuild-std=core --no-default-features --target=xtensa-${{ matrix.chip }}-none-elf --features=${{ matrix.chip }},${{ matrix.printer }}

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
