name: CI

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-riscv:
    name: Check RISC-V
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]
        printer: ["uart"]
        include:
          - chip: esp32c3
            printer: "jtag_serial"
          - chip: esp32c6
            printer: "jtag_serial"
          - chip: esp32h2
            printer: "jtag_serial"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -Zbuild-std=core --no-default-features --target=riscv32imc-unknown-none-elf --features=${{ matrix.chip }},${{ matrix.printer }}

  check-xtensa:
    name: Check Xtensa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [esp32, esp32s2, esp32s3]
        printer: ["uart"]
        include:
          - chip: esp32s3
            printer: "jtag_serial"
    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: false
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -Zbuild-std=core --no-default-features --target=xtensa-${{ matrix.chip }}-none-elf --features=${{ matrix.chip }},${{ matrix.printer }}

  check-log-riscv:
    name: Log drivers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        logger: ["", ",log", ",defmt-espflash"]
        color: [""]
        critical-section: ["", ",critical-section"]
        include:
          - logger: ",log"
            color: ",colors"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -Zbuild-std=core --no-default-features --target=riscv32imc-unknown-none-elf --features=uart,esp32c2${{ matrix.logger }}${{ matrix.color }}${{ matrix.critical-section }}

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
